tpm_core_node:
  ros__parameters:
    robot_type: 100
    a: [0.0,0.0,0.0,0.0,0.0,0.0]
    alpha: [45.0,0.0,0.0,0.0,0.0,0.0]
    d: [392.154, 237.485,  400.0, 39.5, 42.0,0.0]
    theta: [105.0,627.323,0.0,0.0,0.0,0.0]
    pos_limit: [150.0,150.0,150.0]
    neg_limit: [0.0,0.0,0.0]
    pulse_per_unit: [56.513, 56.547, 55.893]
    max_xyz_jog_speed: 40.0
    max_abc_jog_speed: 20.0

    # mnet config
    baudrate: 3     # 0:2.5MHz, 1:5MHz, 2:10MHz, 3:20MHz
    out_mode: 0     # 0:falling-high, 1:rising-high
    ipt_mode: 2     # 0:AB_x1, 1:AB_x2, 2:AB_x4, 3:CW_CCW
    alm_logic: 0    # 0:low active, 1:high active
    org_logic: 0    # 0:low active, 1:high active
    feedback_src: 0 # 0:external. 1:internal
    max_axes_jog_speed: [40.0, 20.0, 20.0, 40.0, 40.0, 40.0] #unit:deg
    home_mode: 0
    home_escape_offset: 1000
    home_offsets: [14.0, 16.0, 14.0, 0.0, 0.0, 0.0] #unit:deg
    home_dir: [0, 0, 0, 0, 0, 0]
