# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.5 #scale (only when execution_duration_monitoring=True)
  allowed_goal_duration_margin: 1.0       #second(only when execution_duration_monitoring=True)
  execution_duration_monitoring: false   #false:turn off timeout check
 
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - tpm_arm_controller

  tpm_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    action_ns: follow_joint_trajectory
    default: true