# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainFormUI.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(980, 500)
        font = QFont()
        font.setFamily(u"Calibri")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        font1 = QFont()
        font1.setFamily(u"Calibri")
        font1.setPointSize(11)
        self.centralwidget.setFont(font1)
        self.grpBox_operation = QGroupBox(self.centralwidget)
        self.grpBox_operation.setObjectName(u"grpBox_operation")
        self.grpBox_operation.setGeometry(QRect(10, 10, 381, 321))
        self.grpBox_operation.setAlignment(Qt.AlignCenter)
        self.radBtn_axis0 = QRadioButton(self.grpBox_operation)
        self.radBtn_axis0.setObjectName(u"radBtn_axis0")
        self.radBtn_axis0.setGeometry(QRect(10, 40, 81, 16))
        self.radBtn_axis0.setChecked(True)
        self.radBtn_axis1 = QRadioButton(self.grpBox_operation)
        self.radBtn_axis1.setObjectName(u"radBtn_axis1")
        self.radBtn_axis1.setGeometry(QRect(10, 70, 83, 16))
        self.radBtn_axis2 = QRadioButton(self.grpBox_operation)
        self.radBtn_axis2.setObjectName(u"radBtn_axis2")
        self.radBtn_axis2.setGeometry(QRect(10, 100, 83, 16))
        self.radBtn_axis2.setChecked(False)
        self.radBtn_axis3 = QRadioButton(self.grpBox_operation)
        self.radBtn_axis3.setObjectName(u"radBtn_axis3")
        self.radBtn_axis3.setGeometry(QRect(10, 130, 83, 16))
        self.radBtn_axis4 = QRadioButton(self.grpBox_operation)
        self.radBtn_axis4.setObjectName(u"radBtn_axis4")
        self.radBtn_axis4.setGeometry(QRect(10, 160, 83, 16))
        self.radBtn_axis5 = QRadioButton(self.grpBox_operation)
        self.radBtn_axis5.setObjectName(u"radBtn_axis5")
        self.radBtn_axis5.setGeometry(QRect(10, 190, 83, 16))
        self.radBtn_axisAll = QRadioButton(self.grpBox_operation)
        self.radBtn_axisAll.setObjectName(u"radBtn_axisAll")
        self.radBtn_axisAll.setGeometry(QRect(10, 220, 83, 16))
        self.btnOp_svon = QPushButton(self.grpBox_operation)
        self.btnOp_svon.setObjectName(u"btnOp_svon")
        self.btnOp_svon.setGeometry(QRect(100, 30, 81, 31))
        self.btnOp_svoff = QPushButton(self.grpBox_operation)
        self.btnOp_svoff.setObjectName(u"btnOp_svoff")
        self.btnOp_svoff.setGeometry(QRect(190, 30, 81, 31))
        self.btnOp_home = QPushButton(self.grpBox_operation)
        self.btnOp_home.setObjectName(u"btnOp_home")
        self.btnOp_home.setGeometry(QRect(100, 110, 81, 31))
        self.btnOp_setToOffset = QPushButton(self.grpBox_operation)
        self.btnOp_setToOffset.setObjectName(u"btnOp_setToOffset")
        self.btnOp_setToOffset.setGeometry(QRect(250, 240, 121, 31))
        self.btnOp_setToZero = QPushButton(self.grpBox_operation)
        self.btnOp_setToZero.setObjectName(u"btnOp_setToZero")
        self.btnOp_setToZero.setGeometry(QRect(250, 280, 121, 31))
        self.btnOp_mvToZero = QPushButton(self.grpBox_operation)
        self.btnOp_mvToZero.setObjectName(u"btnOp_mvToZero")
        self.btnOp_mvToZero.setGeometry(QRect(100, 280, 121, 31))
        self.btnOp_clrAlm = QPushButton(self.grpBox_operation)
        self.btnOp_clrAlm.setObjectName(u"btnOp_clrAlm")
        self.btnOp_clrAlm.setGeometry(QRect(100, 180, 61, 51))
        self.btnOp_jogPos = QPushButton(self.grpBox_operation)
        self.btnOp_jogPos.setObjectName(u"btnOp_jogPos")
        self.btnOp_jogPos.setGeometry(QRect(100, 70, 81, 31))
        self.btnOp_jogNeg = QPushButton(self.grpBox_operation)
        self.btnOp_jogNeg.setObjectName(u"btnOp_jogNeg")
        self.btnOp_jogNeg.setGeometry(QRect(190, 70, 81, 31))
        self.btnOp_stop = QPushButton(self.grpBox_operation)
        self.btnOp_stop.setObjectName(u"btnOp_stop")
        self.btnOp_stop.setGeometry(QRect(190, 110, 81, 31))
        self.btnOp_stop.setAutoFillBackground(False)
        self.sld_speed = QSlider(self.grpBox_operation)
        self.sld_speed.setObjectName(u"sld_speed")
        self.sld_speed.setGeometry(QRect(200, 200, 171, 20))
        self.sld_speed.setMaximum(100)
        self.sld_speed.setSingleStep(10)
        self.sld_speed.setOrientation(Qt.Horizontal)
        self.sld_speed.setTickPosition(QSlider.TicksBelow)
        self.sld_speed.setTickInterval(10)
        self.label = QLabel(self.grpBox_operation)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(250, 180, 61, 16))
        self.label_2 = QLabel(self.grpBox_operation)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(330, 180, 51, 16))
        self.label_3 = QLabel(self.grpBox_operation)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(190, 180, 51, 16))
        self.grpBox_JogDist = QGroupBox(self.grpBox_operation)
        self.grpBox_JogDist.setObjectName(u"grpBox_JogDist")
        self.grpBox_JogDist.setGeometry(QRect(280, 30, 101, 121))
        self.radBtn_jogDist_0 = QRadioButton(self.grpBox_JogDist)
        self.radBtn_jogDist_0.setObjectName(u"radBtn_jogDist_0")
        self.radBtn_jogDist_0.setGeometry(QRect(10, 30, 71, 16))
        self.radBtn_jogDist_0.setChecked(True)
        self.radBtn_jogDist_1 = QRadioButton(self.grpBox_JogDist)
        self.radBtn_jogDist_1.setObjectName(u"radBtn_jogDist_1")
        self.radBtn_jogDist_1.setGeometry(QRect(10, 50, 71, 16))
        self.radBtn_jogDist_1.setChecked(False)
        self.radBtn_jogDist_2 = QRadioButton(self.grpBox_JogDist)
        self.radBtn_jogDist_2.setObjectName(u"radBtn_jogDist_2")
        self.radBtn_jogDist_2.setGeometry(QRect(10, 70, 71, 16))
        self.radBtn_jogDist_2.setChecked(False)
        self.radBtn_jogDist_3 = QRadioButton(self.grpBox_JogDist)
        self.radBtn_jogDist_3.setObjectName(u"radBtn_jogDist_3")
        self.radBtn_jogDist_3.setGeometry(QRect(10, 90, 61, 16))
        self.radBtn_jogDist_3.setChecked(False)
        self.btnOp_find_ORG = QPushButton(self.grpBox_operation)
        self.btnOp_find_ORG.setObjectName(u"btnOp_find_ORG")
        self.btnOp_find_ORG.setGeometry(QRect(100, 240, 121, 31))
        self.checkBox_mvZeroAfterHm = QCheckBox(self.grpBox_operation)
        self.checkBox_mvZeroAfterHm.setObjectName(u"checkBox_mvZeroAfterHm")
        self.checkBox_mvZeroAfterHm.setGeometry(QRect(100, 145, 181, 18))
        self.grpBox_monitor = QGroupBox(self.centralwidget)
        self.grpBox_monitor.setObjectName(u"grpBox_monitor")
        self.grpBox_monitor.setGeometry(QRect(390, 10, 581, 481))
        self.grpBox_monitor.setAlignment(Qt.AlignCenter)
        self.verticalLayout = QVBoxLayout(self.grpBox_monitor)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.led_svo2 = QLabel(self.grpBox_monitor)
        self.led_svo2.setObjectName(u"led_svo2")
        self.led_svo2.setMouseTracking(False)
        self.led_svo2.setAutoFillBackground(True)
        self.led_svo2.setStyleSheet(u"")
        self.led_svo2.setFrameShape(QFrame.Panel)
        self.led_svo2.setFrameShadow(QFrame.Sunken)
        self.led_svo2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_svo2, 1, 3, 1, 1)

        self.txt_pos1 = QLineEdit(self.grpBox_monitor)
        self.txt_pos1.setObjectName(u"txt_pos1")
        font2 = QFont()
        font2.setFamily(u"Calibri")
        font2.setPointSize(15)
        self.txt_pos1.setFont(font2)
        self.txt_pos1.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_pos1, 7, 2, 1, 1)

        self.txt_hmOff1 = QLineEdit(self.grpBox_monitor)
        self.txt_hmOff1.setObjectName(u"txt_hmOff1")
        self.txt_hmOff1.setFont(font2)
        self.txt_hmOff1.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_hmOff1, 9, 2, 1, 1)

        self.txt_psl4 = QLineEdit(self.grpBox_monitor)
        self.txt_psl4.setObjectName(u"txt_psl4")
        self.txt_psl4.setFont(font2)
        self.txt_psl4.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_psl4, 10, 5, 1, 1)

        self.txt_cmd4 = QLineEdit(self.grpBox_monitor)
        self.txt_cmd4.setObjectName(u"txt_cmd4")
        self.txt_cmd4.setFont(font2)
        self.txt_cmd4.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_cmd4, 8, 5, 1, 1)

        self.txt_hmOff4 = QLineEdit(self.grpBox_monitor)
        self.txt_hmOff4.setObjectName(u"txt_hmOff4")
        self.txt_hmOff4.setFont(font2)
        self.txt_hmOff4.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_hmOff4, 9, 5, 1, 1)

        self.label_114 = QLabel(self.grpBox_monitor)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setFrameShape(QFrame.Panel)
        self.label_114.setFrameShadow(QFrame.Sunken)
        self.label_114.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_114, 0, 6, 1, 1)

        self.led_pel0 = QLabel(self.grpBox_monitor)
        self.led_pel0.setObjectName(u"led_pel0")
        self.led_pel0.setMouseTracking(False)
        self.led_pel0.setAutoFillBackground(True)
        self.led_pel0.setStyleSheet(u"")
        self.led_pel0.setFrameShape(QFrame.Panel)
        self.led_pel0.setFrameShadow(QFrame.Sunken)
        self.led_pel0.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_pel0, 3, 1, 1, 1)

        self.label_5 = QLabel(self.grpBox_monitor)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_5, 11, 0, 1, 1)

        self.txt_pos5 = QLineEdit(self.grpBox_monitor)
        self.txt_pos5.setObjectName(u"txt_pos5")
        self.txt_pos5.setFont(font2)
        self.txt_pos5.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_pos5, 7, 6, 1, 1)

        self.label_113 = QLabel(self.grpBox_monitor)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setFrameShape(QFrame.Panel)
        self.label_113.setFrameShadow(QFrame.Sunken)
        self.label_113.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_113, 8, 0, 1, 1)

        self.led_alm4 = QLabel(self.grpBox_monitor)
        self.led_alm4.setObjectName(u"led_alm4")
        self.led_alm4.setMouseTracking(False)
        self.led_alm4.setAutoFillBackground(True)
        self.led_alm4.setStyleSheet(u"")
        self.led_alm4.setFrameShape(QFrame.Panel)
        self.led_alm4.setFrameShadow(QFrame.Sunken)
        self.led_alm4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_alm4, 5, 5, 1, 1)

        self.txt_deg1 = QLineEdit(self.grpBox_monitor)
        self.txt_deg1.setObjectName(u"txt_deg1")
        self.txt_deg1.setFont(font2)
        self.txt_deg1.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_deg1, 6, 2, 1, 1)

        self.txt_cmd3 = QLineEdit(self.grpBox_monitor)
        self.txt_cmd3.setObjectName(u"txt_cmd3")
        self.txt_cmd3.setFont(font2)
        self.txt_cmd3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_cmd3, 8, 4, 1, 1)

        self.led_nel0 = QLabel(self.grpBox_monitor)
        self.led_nel0.setObjectName(u"led_nel0")
        self.led_nel0.setMouseTracking(False)
        self.led_nel0.setAutoFillBackground(True)
        self.led_nel0.setStyleSheet(u"")
        self.led_nel0.setFrameShape(QFrame.Panel)
        self.led_nel0.setFrameShadow(QFrame.Sunken)
        self.led_nel0.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_nel0, 4, 1, 1, 1)

        self.led_org2 = QLabel(self.grpBox_monitor)
        self.led_org2.setObjectName(u"led_org2")
        self.led_org2.setMouseTracking(False)
        self.led_org2.setAutoFillBackground(True)
        self.led_org2.setStyleSheet(u"")
        self.led_org2.setFrameShape(QFrame.Panel)
        self.led_org2.setFrameShadow(QFrame.Sunken)
        self.led_org2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_org2, 2, 3, 1, 1)

        self.led_org4 = QLabel(self.grpBox_monitor)
        self.led_org4.setObjectName(u"led_org4")
        self.led_org4.setMouseTracking(False)
        self.led_org4.setAutoFillBackground(True)
        self.led_org4.setStyleSheet(u"")
        self.led_org4.setFrameShape(QFrame.Panel)
        self.led_org4.setFrameShadow(QFrame.Sunken)
        self.led_org4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_org4, 2, 5, 1, 1)

        self.txt_deg0 = QLineEdit(self.grpBox_monitor)
        self.txt_deg0.setObjectName(u"txt_deg0")
        self.txt_deg0.setFont(font2)
        self.txt_deg0.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_deg0, 6, 1, 1, 1)

        self.txt_cmd0 = QLineEdit(self.grpBox_monitor)
        self.txt_cmd0.setObjectName(u"txt_cmd0")
        self.txt_cmd0.setFont(font2)
        self.txt_cmd0.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_cmd0, 8, 1, 1, 1)

        self.txt_deg3 = QLineEdit(self.grpBox_monitor)
        self.txt_deg3.setObjectName(u"txt_deg3")
        self.txt_deg3.setFont(font2)
        self.txt_deg3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_deg3, 6, 4, 1, 1)

        self.led_org3 = QLabel(self.grpBox_monitor)
        self.led_org3.setObjectName(u"led_org3")
        self.led_org3.setMouseTracking(False)
        self.led_org3.setAutoFillBackground(True)
        self.led_org3.setStyleSheet(u"")
        self.led_org3.setFrameShape(QFrame.Panel)
        self.led_org3.setFrameShadow(QFrame.Sunken)
        self.led_org3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_org3, 2, 4, 1, 1)

        self.txt_cmd5 = QLineEdit(self.grpBox_monitor)
        self.txt_cmd5.setObjectName(u"txt_cmd5")
        self.txt_cmd5.setFont(font2)
        self.txt_cmd5.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_cmd5, 8, 6, 1, 1)

        self.txt_cmd1 = QLineEdit(self.grpBox_monitor)
        self.txt_cmd1.setObjectName(u"txt_cmd1")
        self.txt_cmd1.setFont(font2)
        self.txt_cmd1.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_cmd1, 8, 2, 1, 1)

        self.led_alm1 = QLabel(self.grpBox_monitor)
        self.led_alm1.setObjectName(u"led_alm1")
        self.led_alm1.setMouseTracking(False)
        self.led_alm1.setAutoFillBackground(True)
        self.led_alm1.setStyleSheet(u"")
        self.led_alm1.setFrameShape(QFrame.Panel)
        self.led_alm1.setFrameShadow(QFrame.Sunken)
        self.led_alm1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_alm1, 5, 2, 1, 1)

        self.led_org5 = QLabel(self.grpBox_monitor)
        self.led_org5.setObjectName(u"led_org5")
        self.led_org5.setMouseTracking(False)
        self.led_org5.setAutoFillBackground(True)
        self.led_org5.setStyleSheet(u"")
        self.led_org5.setFrameShape(QFrame.Panel)
        self.led_org5.setFrameShadow(QFrame.Sunken)
        self.led_org5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_org5, 2, 6, 1, 1)

        self.label_122 = QLabel(self.grpBox_monitor)
        self.label_122.setObjectName(u"label_122")
        self.label_122.setFrameShape(QFrame.Panel)
        self.label_122.setFrameShadow(QFrame.Sunken)
        self.label_122.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_122, 5, 0, 1, 1)

        self.txt_hmOff0 = QLineEdit(self.grpBox_monitor)
        self.txt_hmOff0.setObjectName(u"txt_hmOff0")
        self.txt_hmOff0.setFont(font2)
        self.txt_hmOff0.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_hmOff0, 9, 1, 1, 1)

        self.led_svo3 = QLabel(self.grpBox_monitor)
        self.led_svo3.setObjectName(u"led_svo3")
        self.led_svo3.setMouseTracking(False)
        self.led_svo3.setAutoFillBackground(True)
        self.led_svo3.setStyleSheet(u"")
        self.led_svo3.setFrameShape(QFrame.Panel)
        self.led_svo3.setFrameShadow(QFrame.Sunken)
        self.led_svo3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_svo3, 1, 4, 1, 1)

        self.led_nel2 = QLabel(self.grpBox_monitor)
        self.led_nel2.setObjectName(u"led_nel2")
        self.led_nel2.setMouseTracking(False)
        self.led_nel2.setAutoFillBackground(True)
        self.led_nel2.setStyleSheet(u"")
        self.led_nel2.setFrameShape(QFrame.Panel)
        self.led_nel2.setFrameShadow(QFrame.Sunken)
        self.led_nel2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_nel2, 4, 3, 1, 1)

        self.txt_pos2 = QLineEdit(self.grpBox_monitor)
        self.txt_pos2.setObjectName(u"txt_pos2")
        self.txt_pos2.setFont(font2)
        self.txt_pos2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_pos2, 7, 3, 1, 1)

        self.led_alm2 = QLabel(self.grpBox_monitor)
        self.led_alm2.setObjectName(u"led_alm2")
        self.led_alm2.setMouseTracking(False)
        self.led_alm2.setAutoFillBackground(True)
        self.led_alm2.setStyleSheet(u"")
        self.led_alm2.setFrameShape(QFrame.Panel)
        self.led_alm2.setFrameShadow(QFrame.Sunken)
        self.led_alm2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_alm2, 5, 3, 1, 1)

        self.led_pel1 = QLabel(self.grpBox_monitor)
        self.led_pel1.setObjectName(u"led_pel1")
        self.led_pel1.setMouseTracking(False)
        self.led_pel1.setAutoFillBackground(True)
        self.led_pel1.setStyleSheet(u"")
        self.led_pel1.setFrameShape(QFrame.Panel)
        self.led_pel1.setFrameShadow(QFrame.Sunken)
        self.led_pel1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_pel1, 3, 2, 1, 1)

        self.label_95 = QLabel(self.grpBox_monitor)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setFrameShape(QFrame.Panel)
        self.label_95.setFrameShadow(QFrame.Sunken)
        self.label_95.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_95, 7, 0, 1, 1)

        self.txt_psl1 = QLineEdit(self.grpBox_monitor)
        self.txt_psl1.setObjectName(u"txt_psl1")
        self.txt_psl1.setFont(font2)
        self.txt_psl1.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_psl1, 10, 2, 1, 1)

        self.txt_cmd2 = QLineEdit(self.grpBox_monitor)
        self.txt_cmd2.setObjectName(u"txt_cmd2")
        self.txt_cmd2.setFont(font2)
        self.txt_cmd2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_cmd2, 8, 3, 1, 1)

        self.led_pel2 = QLabel(self.grpBox_monitor)
        self.led_pel2.setObjectName(u"led_pel2")
        self.led_pel2.setMouseTracking(False)
        self.led_pel2.setAutoFillBackground(True)
        self.led_pel2.setStyleSheet(u"")
        self.led_pel2.setFrameShape(QFrame.Panel)
        self.led_pel2.setFrameShadow(QFrame.Sunken)
        self.led_pel2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_pel2, 3, 3, 1, 1)

        self.txt_psl3 = QLineEdit(self.grpBox_monitor)
        self.txt_psl3.setObjectName(u"txt_psl3")
        self.txt_psl3.setFont(font2)
        self.txt_psl3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_psl3, 10, 4, 1, 1)

        self.txt_psl5 = QLineEdit(self.grpBox_monitor)
        self.txt_psl5.setObjectName(u"txt_psl5")
        self.txt_psl5.setFont(font2)
        self.txt_psl5.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_psl5, 10, 6, 1, 1)

        self.label_68 = QLabel(self.grpBox_monitor)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setFrameShape(QFrame.Panel)
        self.label_68.setFrameShadow(QFrame.Sunken)
        self.label_68.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_68, 1, 0, 1, 1)

        self.label_83 = QLabel(self.grpBox_monitor)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setFrameShape(QFrame.Panel)
        self.label_83.setFrameShadow(QFrame.Sunken)
        self.label_83.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_83, 6, 0, 1, 1)

        self.led_alm0 = QLabel(self.grpBox_monitor)
        self.led_alm0.setObjectName(u"led_alm0")
        self.led_alm0.setMouseTracking(False)
        self.led_alm0.setAutoFillBackground(True)
        self.led_alm0.setStyleSheet(u"")
        self.led_alm0.setFrameShape(QFrame.Panel)
        self.led_alm0.setFrameShadow(QFrame.Sunken)
        self.led_alm0.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_alm0, 5, 1, 1, 1)

        self.led_pel3 = QLabel(self.grpBox_monitor)
        self.led_pel3.setObjectName(u"led_pel3")
        self.led_pel3.setMouseTracking(False)
        self.led_pel3.setAutoFillBackground(True)
        self.led_pel3.setStyleSheet(u"")
        self.led_pel3.setFrameShape(QFrame.Panel)
        self.led_pel3.setFrameShadow(QFrame.Sunken)
        self.led_pel3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_pel3, 3, 4, 1, 1)

        self.txt_hmOff2 = QLineEdit(self.grpBox_monitor)
        self.txt_hmOff2.setObjectName(u"txt_hmOff2")
        self.txt_hmOff2.setFont(font2)
        self.txt_hmOff2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_hmOff2, 9, 3, 1, 1)

        self.led_nel4 = QLabel(self.grpBox_monitor)
        self.led_nel4.setObjectName(u"led_nel4")
        self.led_nel4.setMouseTracking(False)
        self.led_nel4.setAutoFillBackground(True)
        self.led_nel4.setStyleSheet(u"")
        self.led_nel4.setFrameShape(QFrame.Panel)
        self.led_nel4.setFrameShadow(QFrame.Sunken)
        self.led_nel4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_nel4, 4, 5, 1, 1)

        self.label_4 = QLabel(self.grpBox_monitor)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_4, 10, 0, 1, 1)

        self.led_pel4 = QLabel(self.grpBox_monitor)
        self.led_pel4.setObjectName(u"led_pel4")
        self.led_pel4.setMouseTracking(False)
        self.led_pel4.setAutoFillBackground(True)
        self.led_pel4.setStyleSheet(u"")
        self.led_pel4.setFrameShape(QFrame.Panel)
        self.led_pel4.setFrameShadow(QFrame.Sunken)
        self.led_pel4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_pel4, 3, 5, 1, 1)

        self.led_svo4 = QLabel(self.grpBox_monitor)
        self.led_svo4.setObjectName(u"led_svo4")
        self.led_svo4.setMouseTracking(False)
        self.led_svo4.setAutoFillBackground(True)
        self.led_svo4.setStyleSheet(u"")
        self.led_svo4.setFrameShape(QFrame.Panel)
        self.led_svo4.setFrameShadow(QFrame.Sunken)
        self.led_svo4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_svo4, 1, 5, 1, 1)

        self.led_alm5 = QLabel(self.grpBox_monitor)
        self.led_alm5.setObjectName(u"led_alm5")
        self.led_alm5.setMouseTracking(False)
        self.led_alm5.setAutoFillBackground(True)
        self.led_alm5.setStyleSheet(u"")
        self.led_alm5.setFrameShape(QFrame.Panel)
        self.led_alm5.setFrameShadow(QFrame.Sunken)
        self.led_alm5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_alm5, 5, 6, 1, 1)

        self.txt_deg4 = QLineEdit(self.grpBox_monitor)
        self.txt_deg4.setObjectName(u"txt_deg4")
        self.txt_deg4.setFont(font2)
        self.txt_deg4.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_deg4, 6, 5, 1, 1)

        self.led_org0 = QLabel(self.grpBox_monitor)
        self.led_org0.setObjectName(u"led_org0")
        self.led_org0.setMouseTracking(False)
        self.led_org0.setAutoFillBackground(True)
        self.led_org0.setStyleSheet(u"")
        self.led_org0.setFrameShape(QFrame.Panel)
        self.led_org0.setFrameShadow(QFrame.Sunken)
        self.led_org0.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_org0, 2, 1, 1, 1)

        self.label_105 = QLabel(self.grpBox_monitor)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setFrameShape(QFrame.Panel)
        self.label_105.setFrameShadow(QFrame.Sunken)
        self.label_105.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_105, 0, 3, 1, 1)

        self.txt_pos4 = QLineEdit(self.grpBox_monitor)
        self.txt_pos4.setObjectName(u"txt_pos4")
        self.txt_pos4.setFont(font2)
        self.txt_pos4.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_pos4, 7, 5, 1, 1)

        self.txt_hmOff5 = QLineEdit(self.grpBox_monitor)
        self.txt_hmOff5.setObjectName(u"txt_hmOff5")
        self.txt_hmOff5.setFont(font2)
        self.txt_hmOff5.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_hmOff5, 9, 6, 1, 1)

        self.txt_psl2 = QLineEdit(self.grpBox_monitor)
        self.txt_psl2.setObjectName(u"txt_psl2")
        self.txt_psl2.setFont(font2)
        self.txt_psl2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_psl2, 10, 3, 1, 1)

        self.txt_deg5 = QLineEdit(self.grpBox_monitor)
        self.txt_deg5.setObjectName(u"txt_deg5")
        self.txt_deg5.setFont(font2)
        self.txt_deg5.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_deg5, 6, 6, 1, 1)

        self.label_102 = QLabel(self.grpBox_monitor)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setFrameShape(QFrame.Panel)
        self.label_102.setFrameShadow(QFrame.Sunken)
        self.label_102.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_102, 3, 0, 1, 1)

        self.label_118 = QLabel(self.grpBox_monitor)
        self.label_118.setObjectName(u"label_118")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_118.sizePolicy().hasHeightForWidth())
        self.label_118.setSizePolicy(sizePolicy)
        font3 = QFont()
        font3.setFamily(u"Calibri")
        font3.setPointSize(11)
        font3.setKerning(True)
        self.label_118.setFont(font3)
        self.label_118.setFrameShape(QFrame.Panel)
        self.label_118.setFrameShadow(QFrame.Sunken)
        self.label_118.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_118, 9, 0, 1, 1)

        self.label_85 = QLabel(self.grpBox_monitor)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setFrameShape(QFrame.Panel)
        self.label_85.setFrameShadow(QFrame.Sunken)
        self.label_85.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_85, 4, 0, 1, 1)

        self.led_svo5 = QLabel(self.grpBox_monitor)
        self.led_svo5.setObjectName(u"led_svo5")
        self.led_svo5.setMouseTracking(False)
        self.led_svo5.setAutoFillBackground(True)
        self.led_svo5.setStyleSheet(u"")
        self.led_svo5.setFrameShape(QFrame.Panel)
        self.led_svo5.setFrameShadow(QFrame.Sunken)
        self.led_svo5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_svo5, 1, 6, 1, 1)

        self.txt_psl0 = QLineEdit(self.grpBox_monitor)
        self.txt_psl0.setObjectName(u"txt_psl0")
        self.txt_psl0.setFont(font2)
        self.txt_psl0.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_psl0, 10, 1, 1, 1)

        self.label_66 = QLabel(self.grpBox_monitor)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setFrameShape(QFrame.Panel)
        self.label_66.setFrameShadow(QFrame.Sunken)
        self.label_66.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_66, 0, 1, 1, 1)

        self.label_71 = QLabel(self.grpBox_monitor)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setFrameShape(QFrame.Panel)
        self.label_71.setFrameShadow(QFrame.Sunken)
        self.label_71.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_71, 2, 0, 1, 1)

        self.led_svo1 = QLabel(self.grpBox_monitor)
        self.led_svo1.setObjectName(u"led_svo1")
        self.led_svo1.setMouseTracking(False)
        self.led_svo1.setAutoFillBackground(True)
        self.led_svo1.setStyleSheet(u"")
        self.led_svo1.setFrameShape(QFrame.Panel)
        self.led_svo1.setFrameShadow(QFrame.Sunken)
        self.led_svo1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_svo1, 1, 2, 1, 1)

        self.led_nel3 = QLabel(self.grpBox_monitor)
        self.led_nel3.setObjectName(u"led_nel3")
        self.led_nel3.setMouseTracking(False)
        self.led_nel3.setAutoFillBackground(True)
        self.led_nel3.setStyleSheet(u"")
        self.led_nel3.setFrameShape(QFrame.Panel)
        self.led_nel3.setFrameShadow(QFrame.Sunken)
        self.led_nel3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_nel3, 4, 4, 1, 1)

        self.txt_deg2 = QLineEdit(self.grpBox_monitor)
        self.txt_deg2.setObjectName(u"txt_deg2")
        self.txt_deg2.setFont(font2)
        self.txt_deg2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_deg2, 6, 3, 1, 1)

        self.txt_pos3 = QLineEdit(self.grpBox_monitor)
        self.txt_pos3.setObjectName(u"txt_pos3")
        self.txt_pos3.setFont(font2)
        self.txt_pos3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_pos3, 7, 4, 1, 1)

        self.label_128 = QLabel(self.grpBox_monitor)
        self.label_128.setObjectName(u"label_128")
        self.label_128.setFrameShape(QFrame.Panel)
        self.label_128.setFrameShadow(QFrame.Sunken)
        self.label_128.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_128, 0, 5, 1, 1)

        self.led_alm3 = QLabel(self.grpBox_monitor)
        self.led_alm3.setObjectName(u"led_alm3")
        self.led_alm3.setMouseTracking(False)
        self.led_alm3.setAutoFillBackground(True)
        self.led_alm3.setStyleSheet(u"")
        self.led_alm3.setFrameShape(QFrame.Panel)
        self.led_alm3.setFrameShadow(QFrame.Sunken)
        self.led_alm3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_alm3, 5, 4, 1, 1)

        self.label_88 = QLabel(self.grpBox_monitor)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setFrameShape(QFrame.Panel)
        self.label_88.setFrameShadow(QFrame.Sunken)
        self.label_88.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_88, 0, 2, 1, 1)

        self.led_nel5 = QLabel(self.grpBox_monitor)
        self.led_nel5.setObjectName(u"led_nel5")
        self.led_nel5.setMouseTracking(False)
        self.led_nel5.setAutoFillBackground(True)
        self.led_nel5.setStyleSheet(u"")
        self.led_nel5.setFrameShape(QFrame.Panel)
        self.led_nel5.setFrameShadow(QFrame.Sunken)
        self.led_nel5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_nel5, 4, 6, 1, 1)

        self.txt_pos0 = QLineEdit(self.grpBox_monitor)
        self.txt_pos0.setObjectName(u"txt_pos0")
        self.txt_pos0.setFont(font2)
        self.txt_pos0.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_pos0, 7, 1, 1, 1)

        self.led_svo0 = QLabel(self.grpBox_monitor)
        self.led_svo0.setObjectName(u"led_svo0")
        self.led_svo0.setMouseTracking(False)
        self.led_svo0.setAutoFillBackground(True)
        self.led_svo0.setStyleSheet(u"")
        self.led_svo0.setFrameShape(QFrame.Panel)
        self.led_svo0.setFrameShadow(QFrame.Sunken)
        self.led_svo0.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_svo0, 1, 1, 1, 1)

        self.led_org1 = QLabel(self.grpBox_monitor)
        self.led_org1.setObjectName(u"led_org1")
        self.led_org1.setMouseTracking(False)
        self.led_org1.setAutoFillBackground(True)
        self.led_org1.setStyleSheet(u"")
        self.led_org1.setFrameShape(QFrame.Panel)
        self.led_org1.setFrameShadow(QFrame.Sunken)
        self.led_org1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_org1, 2, 2, 1, 1)

        self.txt_hmOff3 = QLineEdit(self.grpBox_monitor)
        self.txt_hmOff3.setObjectName(u"txt_hmOff3")
        self.txt_hmOff3.setFont(font2)
        self.txt_hmOff3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_hmOff3, 9, 4, 1, 1)

        self.label_117 = QLabel(self.grpBox_monitor)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setFrameShape(QFrame.Panel)
        self.label_117.setFrameShadow(QFrame.Sunken)
        self.label_117.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.label_117, 0, 4, 1, 1)

        self.led_pel5 = QLabel(self.grpBox_monitor)
        self.led_pel5.setObjectName(u"led_pel5")
        self.led_pel5.setMouseTracking(False)
        self.led_pel5.setAutoFillBackground(True)
        self.led_pel5.setStyleSheet(u"")
        self.led_pel5.setFrameShape(QFrame.Panel)
        self.led_pel5.setFrameShadow(QFrame.Sunken)
        self.led_pel5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_pel5, 3, 6, 1, 1)

        self.led_nel1 = QLabel(self.grpBox_monitor)
        self.led_nel1.setObjectName(u"led_nel1")
        self.led_nel1.setMouseTracking(False)
        self.led_nel1.setAutoFillBackground(True)
        self.led_nel1.setStyleSheet(u"")
        self.led_nel1.setFrameShape(QFrame.Panel)
        self.led_nel1.setFrameShadow(QFrame.Sunken)
        self.led_nel1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.led_nel1, 4, 2, 1, 1)

        self.txt_nsl0 = QLineEdit(self.grpBox_monitor)
        self.txt_nsl0.setObjectName(u"txt_nsl0")
        self.txt_nsl0.setFont(font2)
        self.txt_nsl0.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_nsl0, 11, 1, 1, 1)

        self.txt_nsl1 = QLineEdit(self.grpBox_monitor)
        self.txt_nsl1.setObjectName(u"txt_nsl1")
        self.txt_nsl1.setFont(font2)
        self.txt_nsl1.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_nsl1, 11, 2, 1, 1)

        self.txt_nsl2 = QLineEdit(self.grpBox_monitor)
        self.txt_nsl2.setObjectName(u"txt_nsl2")
        self.txt_nsl2.setFont(font2)
        self.txt_nsl2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_nsl2, 11, 3, 1, 1)

        self.txt_nsl3 = QLineEdit(self.grpBox_monitor)
        self.txt_nsl3.setObjectName(u"txt_nsl3")
        self.txt_nsl3.setFont(font2)
        self.txt_nsl3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_nsl3, 11, 4, 1, 1)

        self.txt_nsl4 = QLineEdit(self.grpBox_monitor)
        self.txt_nsl4.setObjectName(u"txt_nsl4")
        self.txt_nsl4.setFont(font2)
        self.txt_nsl4.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_nsl4, 11, 5, 1, 1)

        self.txt_nsl5 = QLineEdit(self.grpBox_monitor)
        self.txt_nsl5.setObjectName(u"txt_nsl5")
        self.txt_nsl5.setFont(font2)
        self.txt_nsl5.setReadOnly(True)

        self.gridLayout_2.addWidget(self.txt_nsl5, 11, 6, 1, 1)

        self.gridLayout_2.setRowStretch(0, 7)
        self.gridLayout_2.setRowStretch(1, 8)
        self.gridLayout_2.setRowStretch(2, 8)
        self.gridLayout_2.setRowStretch(3, 8)
        self.gridLayout_2.setRowStretch(4, 8)
        self.gridLayout_2.setRowStretch(5, 8)
        self.gridLayout_2.setRowStretch(6, 10)
        self.gridLayout_2.setRowStretch(7, 10)
        self.gridLayout_2.setRowStretch(8, 10)
        self.gridLayout_2.setRowStretch(9, 10)
        self.gridLayout_2.setRowStretch(10, 10)
        self.gridLayout_2.setRowStretch(11, 10)
        self.gridLayout_2.setColumnStretch(0, 6)
        self.gridLayout_2.setColumnStretch(1, 10)
        self.gridLayout_2.setColumnStretch(2, 10)
        self.gridLayout_2.setColumnStretch(3, 10)
        self.gridLayout_2.setColumnStretch(4, 10)
        self.gridLayout_2.setColumnStretch(5, 10)
        self.gridLayout_2.setColumnStretch(6, 10)

        self.verticalLayout.addLayout(self.gridLayout_2)

        self.grpBox_poseJog = QGroupBox(self.centralwidget)
        self.grpBox_poseJog.setObjectName(u"grpBox_poseJog")
        self.grpBox_poseJog.setGeometry(QRect(0, 340, 381, 151))
        self.grpBox_poseJog.setAlignment(Qt.AlignCenter)
        self.radBtn_poseX = QRadioButton(self.grpBox_poseJog)
        self.radBtn_poseX.setObjectName(u"radBtn_poseX")
        self.radBtn_poseX.setGeometry(QRect(10, 40, 31, 18))
        self.radBtn_poseX.setChecked(True)
        self.radBtn_poseY = QRadioButton(self.grpBox_poseJog)
        self.radBtn_poseY.setObjectName(u"radBtn_poseY")
        self.radBtn_poseY.setGeometry(QRect(10, 80, 31, 18))
        self.radBtn_poseZ = QRadioButton(self.grpBox_poseJog)
        self.radBtn_poseZ.setObjectName(u"radBtn_poseZ")
        self.radBtn_poseZ.setGeometry(QRect(10, 120, 31, 18))
        self.radBtn_poseC = QRadioButton(self.grpBox_poseJog)
        self.radBtn_poseC.setObjectName(u"radBtn_poseC")
        self.radBtn_poseC.setGeometry(QRect(150, 120, 31, 18))
        self.radBtn_poseA = QRadioButton(self.grpBox_poseJog)
        self.radBtn_poseA.setObjectName(u"radBtn_poseA")
        self.radBtn_poseA.setGeometry(QRect(150, 40, 31, 18))
        self.radBtn_poseB = QRadioButton(self.grpBox_poseJog)
        self.radBtn_poseB.setObjectName(u"radBtn_poseB")
        self.radBtn_poseB.setGeometry(QRect(150, 80, 31, 18))
        self.txt_poseX = QLineEdit(self.grpBox_poseJog)
        self.txt_poseX.setObjectName(u"txt_poseX")
        self.txt_poseX.setGeometry(QRect(50, 40, 81, 20))
        font4 = QFont()
        font4.setFamily(u"Calibri")
        font4.setPointSize(13)
        self.txt_poseX.setFont(font4)
        self.txt_poseX.setReadOnly(True)
        self.txt_poseY = QLineEdit(self.grpBox_poseJog)
        self.txt_poseY.setObjectName(u"txt_poseY")
        self.txt_poseY.setGeometry(QRect(50, 80, 81, 20))
        self.txt_poseY.setFont(font4)
        self.txt_poseY.setReadOnly(True)
        self.txt_poseZ = QLineEdit(self.grpBox_poseJog)
        self.txt_poseZ.setObjectName(u"txt_poseZ")
        self.txt_poseZ.setGeometry(QRect(50, 120, 81, 20))
        self.txt_poseZ.setFont(font4)
        self.txt_poseZ.setReadOnly(True)
        self.txt_poseC = QLineEdit(self.grpBox_poseJog)
        self.txt_poseC.setObjectName(u"txt_poseC")
        self.txt_poseC.setGeometry(QRect(190, 120, 81, 20))
        self.txt_poseC.setFont(font4)
        self.txt_poseC.setReadOnly(True)
        self.txt_poseA = QLineEdit(self.grpBox_poseJog)
        self.txt_poseA.setObjectName(u"txt_poseA")
        self.txt_poseA.setGeometry(QRect(190, 40, 81, 20))
        self.txt_poseA.setFont(font4)
        self.txt_poseA.setReadOnly(True)
        self.txt_poseB = QLineEdit(self.grpBox_poseJog)
        self.txt_poseB.setObjectName(u"txt_poseB")
        self.txt_poseB.setGeometry(QRect(190, 80, 81, 20))
        self.txt_poseB.setFont(font4)
        self.txt_poseB.setReadOnly(True)
        self.btnJog_pos = QPushButton(self.grpBox_poseJog)
        self.btnJog_pos.setObjectName(u"btnJog_pos")
        self.btnJog_pos.setGeometry(QRect(300, 40, 61, 41))
        self.btnJog_neg = QPushButton(self.grpBox_poseJog)
        self.btnJog_neg.setObjectName(u"btnJog_neg")
        self.btnJog_neg.setGeometry(QRect(300, 90, 61, 41))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MyRosRobot", None))
        self.grpBox_operation.setTitle(QCoreApplication.translate("MainWindow", u"Operation", None))
        self.radBtn_axis0.setText(QCoreApplication.translate("MainWindow", u"Axis1", None))
        self.radBtn_axis1.setText(QCoreApplication.translate("MainWindow", u"Axis2", None))
        self.radBtn_axis2.setText(QCoreApplication.translate("MainWindow", u"Axis3", None))
        self.radBtn_axis3.setText(QCoreApplication.translate("MainWindow", u"Axis4", None))
        self.radBtn_axis4.setText(QCoreApplication.translate("MainWindow", u"Axis5", None))
        self.radBtn_axis5.setText(QCoreApplication.translate("MainWindow", u"Axis6", None))
        self.radBtn_axisAll.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.btnOp_svon.setText(QCoreApplication.translate("MainWindow", u"SvOn", None))
        self.btnOp_svoff.setText(QCoreApplication.translate("MainWindow", u"SvOff", None))
        self.btnOp_home.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.btnOp_setToOffset.setText(QCoreApplication.translate("MainWindow", u"Set as offset", None))
        self.btnOp_setToZero.setText(QCoreApplication.translate("MainWindow", u"Set as zero", None))
        self.btnOp_mvToZero.setText(QCoreApplication.translate("MainWindow", u"Move to zero", None))
        self.btnOp_clrAlm.setText(QCoreApplication.translate("MainWindow", u"Clear\n"
"ALM", None))
        self.btnOp_jogPos.setText(QCoreApplication.translate("MainWindow", u"Jog +", None))
        self.btnOp_jogNeg.setText(QCoreApplication.translate("MainWindow", u"Jog -", None))
        self.btnOp_stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Speed", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"100%", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.grpBox_JogDist.setTitle(QCoreApplication.translate("MainWindow", u"Jog Dist", None))
        self.radBtn_jogDist_0.setText(QCoreApplication.translate("MainWindow", u"Inf", None))
        self.radBtn_jogDist_1.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.radBtn_jogDist_2.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.radBtn_jogDist_3.setText(QCoreApplication.translate("MainWindow", u"0.1", None))
        self.btnOp_find_ORG.setText(QCoreApplication.translate("MainWindow", u"Search ORG", None))
        self.checkBox_mvZeroAfterHm.setText(QCoreApplication.translate("MainWindow", u"Move to zero after Home.", None))
        self.grpBox_monitor.setTitle(QCoreApplication.translate("MainWindow", u"Monitor", None))
        self.led_svo2.setText("")
        self.txt_pos1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_hmOff1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_psl4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_cmd4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_hmOff4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_114.setText(QCoreApplication.translate("MainWindow", u"A6", None))
        self.led_pel0.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"NSL", None))
        self.txt_pos5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_113.setText(QCoreApplication.translate("MainWindow", u"Cmd.", None))
        self.led_alm4.setText("")
        self.txt_deg1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_cmd3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.led_nel0.setText("")
        self.led_org2.setText("")
        self.led_org4.setText("")
        self.txt_deg0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_cmd0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_deg3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.led_org3.setText("")
        self.txt_cmd5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_cmd1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.led_alm1.setText("")
        self.led_org5.setText("")
        self.label_122.setText(QCoreApplication.translate("MainWindow", u"ALM", None))
        self.txt_hmOff0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.led_svo3.setText("")
        self.led_nel2.setText("")
        self.txt_pos2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.led_alm2.setText("")
        self.led_pel1.setText("")
        self.label_95.setText(QCoreApplication.translate("MainWindow", u"Pos.", None))
        self.txt_psl1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_cmd2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.led_pel2.setText("")
        self.txt_psl3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_psl5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"SVO", None))
        self.label_83.setText(QCoreApplication.translate("MainWindow", u"Deg.", None))
        self.led_alm0.setText("")
        self.led_pel3.setText("")
        self.txt_hmOff2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.led_nel4.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"PSL", None))
        self.led_pel4.setText("")
        self.led_svo4.setText("")
        self.led_alm5.setText("")
        self.txt_deg4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.led_org0.setText("")
        self.label_105.setText(QCoreApplication.translate("MainWindow", u"A3", None))
        self.txt_pos4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_hmOff5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_psl2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_deg5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_102.setText(QCoreApplication.translate("MainWindow", u"PEL", None))
        self.label_118.setText(QCoreApplication.translate("MainWindow", u"HmOff", None))
        self.label_85.setText(QCoreApplication.translate("MainWindow", u"NEL", None))
        self.led_svo5.setText("")
        self.txt_psl0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"A1", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"ORG", None))
        self.led_svo1.setText("")
        self.led_nel3.setText("")
        self.txt_deg2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_pos3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_128.setText(QCoreApplication.translate("MainWindow", u"A5", None))
        self.led_alm3.setText("")
        self.label_88.setText(QCoreApplication.translate("MainWindow", u"A2", None))
        self.led_nel5.setText("")
        self.txt_pos0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.led_svo0.setText("")
        self.led_org1.setText("")
        self.txt_hmOff3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_117.setText(QCoreApplication.translate("MainWindow", u"A4", None))
        self.led_pel5.setText("")
        self.led_nel1.setText("")
        self.txt_nsl0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_nsl1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_nsl2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_nsl3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_nsl4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_nsl5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.grpBox_poseJog.setTitle(QCoreApplication.translate("MainWindow", u"Pose Jog", None))
        self.radBtn_poseX.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.radBtn_poseY.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.radBtn_poseZ.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.radBtn_poseC.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.radBtn_poseA.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.radBtn_poseB.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.txt_poseX.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_poseY.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_poseZ.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_poseC.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_poseA.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txt_poseB.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.btnJog_pos.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.btnJog_neg.setText(QCoreApplication.translate("MainWindow", u"-", None))
    # retranslateUi

