int8 SERVO_ON = 1
int8 SERVO_OFF = 2
int8 HOME = 3
int8 SET_AS_OFFSET = 4
int8 SET_AS_ZERO = 5
int8 MV_TO_ZERO = 6
int8 CLEAR_ALM = 7
int8 JOG_POS = 8
int8 JOG_NEG = 9
int8 STOP = 10
int8 SEARCH_ORG = 11


int8 axis_id
int8 function
---
bool ok