#-------------------------------------------------------------------------------
# Service request fields
#-------------------------------------------------------------------------------
uint8[] buffer

---

#-------------------------------------------------------------------------------
# Service response fields
#-------------------------------------------------------------------------------
uint8[] buffer

# Service success/failure indicator.
int16 result_code

# Status message (empty if service succeeded).
string message